2025-10-01 00:08:06,342 INFO    MainThread:36 [wandb_setup.py:_flush():81] Current SDK version is 0.20.1
2025-10-01 00:08:06,342 INFO    MainThread:36 [wandb_setup.py:_flush():81] Configure stats pid to 36
2025-10-01 00:08:06,342 INFO    MainThread:36 [wandb_setup.py:_flush():81] Loading settings from /root/.config/wandb/settings
2025-10-01 00:08:06,342 INFO    MainThread:36 [wandb_setup.py:_flush():81] Loading settings from /kaggle/working/wandb/settings
2025-10-01 00:08:06,342 INFO    MainThread:36 [wandb_setup.py:_flush():81] Loading settings from environment variables
2025-10-01 00:08:06,342 INFO    MainThread:36 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /kaggle/working/wandb/run-20251001_000806-08awitdi/logs/debug.log
2025-10-01 00:08:06,342 INFO    MainThread:36 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /kaggle/working/wandb/run-20251001_000806-08awitdi/logs/debug-internal.log
2025-10-01 00:08:06,342 INFO    MainThread:36 [wandb_init.py:monkeypatch_ipython():622] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7a4d20720110>
2025-10-01 00:08:06,343 INFO    MainThread:36 [wandb_init.py:init():831] calling init triggers
2025-10-01 00:08:06,343 INFO    MainThread:36 [wandb_init.py:init():836] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-10-01 00:08:06,343 INFO    MainThread:36 [wandb_init.py:init():872] starting backend
2025-10-01 00:08:06,972 INFO    MainThread:36 [wandb_init.py:init():875] sending inform_init request
2025-10-01 00:08:06,984 INFO    MainThread:36 [wandb_init.py:init():883] backend started and connected
2025-10-01 00:08:06,992 INFO    MainThread:36 [wandb_run.py:_label_probe_notebook():1299] probe notebook
2025-10-01 00:08:12,687 INFO    MainThread:36 [wandb_init.py:init():956] updated telemetry
2025-10-01 00:08:12,688 INFO    MainThread:36 [wandb_init.py:init():980] communicating run to backend with 90.0 second timeout
2025-10-01 00:08:12,886 INFO    MainThread:36 [wandb_init.py:init():1032] starting run threads in backend
2025-10-01 00:08:13,471 INFO    MainThread:36 [wandb_run.py:_console_start():2453] atexit reg
2025-10-01 00:08:13,471 INFO    MainThread:36 [wandb_run.py:_redirect():2301] redirect: wrap_raw
2025-10-01 00:08:13,472 INFO    MainThread:36 [wandb_run.py:_redirect():2370] Wrapping output streams.
2025-10-01 00:08:13,472 INFO    MainThread:36 [wandb_run.py:_redirect():2393] Redirects installed.
2025-10-01 00:08:13,481 INFO    MainThread:36 [wandb_init.py:init():1078] run started, returning control to user process
2025-10-01 00:17:56,103 INFO    MainThread:36 [wandb_init.py:_post_run_cell_hook():592] [no run ID] resuming backend
2025-10-01 00:17:56,482 INFO    MsgRouterThr:36 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-10-01 00:17:56,917 ERROR   Thread-2 (_watch_pipe_fd):36 [redirect.py:_on_write():664] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 2374, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/wandb_run.py", line 1561, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface.py", line 772, in publish_output_raw
    self._publish_output_raw(o)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
